// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rider-dashboard/Bold.tsx": () => import("../components/mockups/rider-dashboard/Bold.tsx"),
  "./components/mockups/rider-dashboard/Current.tsx": () => import("../components/mockups/rider-dashboard/Current.tsx"),
  "./components/mockups/rider-dashboard/Modern.tsx": () => import("../components/mockups/rider-dashboard/Modern.tsx"),
  "./components/mockups/rider-header/V1Glassmorphism.tsx": () => import("../components/mockups/rider-header/V1Glassmorphism.tsx"),
  "./components/mockups/rider-header/V2DarkLogistics.tsx": () => import("../components/mockups/rider-header/V2DarkLogistics.tsx"),
  "./components/mockups/rider-header/V3BrandGradient.tsx": () => import("../components/mockups/rider-header/V3BrandGradient.tsx"),
  "./components/mockups/rider-header/V4MaterialSlate.tsx": () => import("../components/mockups/rider-header/V4MaterialSlate.tsx"),
  "./components/mockups/rider-header/V5TacticalDashboard.tsx": () => import("../components/mockups/rider-header/V5TacticalDashboard.tsx"),
  "./components/mockups/wallet-redesign/BoldGradient.tsx": () => import("../components/mockups/wallet-redesign/BoldGradient.tsx"),
  "./components/mockups/wallet-redesign/GlassmorphismPremium.tsx": () => import("../components/mockups/wallet-redesign/GlassmorphismPremium.tsx"),
  "./components/mockups/wallet-redesign/NeobankMinimal.tsx": () => import("../components/mockups/wallet-redesign/NeobankMinimal.tsx")
};
