// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rider-dashboard/Bold.tsx": () => import("../components/mockups/rider-dashboard/Bold.tsx"),
  "./components/mockups/rider-dashboard/Current.tsx": () => import("../components/mockups/rider-dashboard/Current.tsx"),
  "./components/mockups/rider-dashboard/Modern.tsx": () => import("../components/mockups/rider-dashboard/Modern.tsx"),
  "./components/mockups/rider-header/V1AppleLight.tsx": () => import("../components/mockups/rider-header/V1AppleLight.tsx"),
  "./components/mockups/rider-header/V1Glassmorphism.tsx": () => import("../components/mockups/rider-header/V1Glassmorphism.tsx"),
  "./components/mockups/rider-header/V2AppleDark.tsx": () => import("../components/mockups/rider-header/V2AppleDark.tsx"),
  "./components/mockups/rider-header/V2DarkLogistics.tsx": () => import("../components/mockups/rider-header/V2DarkLogistics.tsx"),
  "./components/mockups/rider-header/V3BinanceDark.tsx": () => import("../components/mockups/rider-header/V3BinanceDark.tsx"),
  "./components/mockups/rider-header/V3BrandGradient.tsx": () => import("../components/mockups/rider-header/V3BrandGradient.tsx"),
  "./components/mockups/rider-header/V4A_HorizontalHero.tsx": () => import("../components/mockups/rider-header/V4A_HorizontalHero.tsx"),
  "./components/mockups/rider-header/V4B_SplitColumn.tsx": () => import("../components/mockups/rider-header/V4B_SplitColumn.tsx"),
  "./components/mockups/rider-header/V4C_FloatingStage.tsx": () => import("../components/mockups/rider-header/V4C_FloatingStage.tsx"),
  "./components/mockups/rider-header/V4MaterialSlate.tsx": () => import("../components/mockups/rider-header/V4MaterialSlate.tsx"),
  "./components/mockups/rider-header/V4PremiumObsidian.tsx": () => import("../components/mockups/rider-header/V4PremiumObsidian.tsx"),
  "./components/mockups/rider-header/V5BinanceLight.tsx": () => import("../components/mockups/rider-header/V5BinanceLight.tsx"),
  "./components/mockups/rider-header/V5TacticalDashboard.tsx": () => import("../components/mockups/rider-header/V5TacticalDashboard.tsx"),
  "./components/mockups/wallet-redesign/BoldGradient.tsx": () => import("../components/mockups/wallet-redesign/BoldGradient.tsx"),
  "./components/mockups/wallet-redesign/GlassmorphismPremium.tsx": () => import("../components/mockups/wallet-redesign/GlassmorphismPremium.tsx"),
  "./components/mockups/wallet-redesign/NeobankMinimal.tsx": () => import("../components/mockups/wallet-redesign/NeobankMinimal.tsx")
};
