-- Migration: Soft-delete columns, FK cascade/onDelete audit, security tables
-- Applied by: runSqlMigrations() at startup
--
-- MIGRATION STRATEGY NOTE
-- This project uses two complementary migration tracks:
--   1. lib/db/drizzle/NNNN_*.sql  — generated by `drizzle-kit generate`;
--      applied automatically via the Drizzle migrator (runDrizzleMigrations).
--   2. lib/db/migrations/NNNN_*.sql — hand-authored idempotent SQL;
--      applied by runSqlMigrations() at startup for DDL that Drizzle cannot
--      safely generate (e.g. FK policy rewrites, large-table backfills).
-- Both tracks are numbered in lockstep. Never apply track-2 files manually
-- outside of the startup runner — runSqlMigrations() guards against replays.

-- 1. Soft-delete column for users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deleted_at" timestamptz;

-- 2. Soft-delete column for products
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "deleted_at" timestamptz;

-- 3. FK from flash_deals.product_id → products.id (cascade delete)
--    Drop old unconstrained column and re-add with FK only if the constraint
--    does not already exist (idempotent via DO block).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'flash_deals_product_id_products_id_fk'
      AND table_name = 'flash_deals'
  ) THEN
    ALTER TABLE "flash_deals"
      ADD CONSTRAINT "flash_deals_product_id_products_id_fk"
      FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE;
  END IF;
END $$;

-- 4. FK onDelete policy audit — 4 bare references now have explicit policies
--    These are idempotent: drop then re-add so existing deployments are updated.

-- 4a. ab_assignments.experiment_id → ab_experiments.id (cascade)
--     Rationale: assignment rows have no meaning without the parent experiment.
DO $$
BEGIN
  ALTER TABLE "ab_assignments" DROP CONSTRAINT IF EXISTS "ab_assignments_experiment_id_ab_experiments_id_fk";
  ALTER TABLE "ab_assignments"
    ADD CONSTRAINT "ab_assignments_experiment_id_ab_experiments_id_fk"
    FOREIGN KEY ("experiment_id") REFERENCES "ab_experiments"("id") ON DELETE CASCADE;
END $$;

-- 4b. call_logs.conversation_id → comm_conversations.id (set null)
DO $$
BEGIN
  ALTER TABLE "call_logs" DROP CONSTRAINT IF EXISTS "call_logs_conversation_id_conversations_id_fk";
  ALTER TABLE "call_logs" DROP CONSTRAINT IF EXISTS "call_logs_conversation_id_comm_conversations_id_fk";
  ALTER TABLE "call_logs"
    ADD CONSTRAINT "call_logs_conversation_id_comm_conversations_id_fk"
    FOREIGN KEY ("conversation_id") REFERENCES "comm_conversations"("id") ON DELETE SET NULL;
END $$;

-- 4c. qr_codes.created_by → users.id (set null)
--     Rationale: QR code records are retained for audit; creator reference cleared on user deletion.
DO $$
BEGIN
  ALTER TABLE "qr_codes" DROP CONSTRAINT IF EXISTS "qr_codes_created_by_users_id_fk";
  ALTER TABLE "qr_codes"
    ADD CONSTRAINT "qr_codes_created_by_users_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL;
END $$;

-- 4d. webhook_logs.webhook_id → webhook_registrations.id (cascade)
--     Rationale: log rows are meaningless without the parent webhook registration.
DO $$
BEGIN
  ALTER TABLE "webhook_logs" DROP CONSTRAINT IF EXISTS "webhook_logs_webhook_id_webhook_registrations_id_fk";
  ALTER TABLE "webhook_logs"
    ADD CONSTRAINT "webhook_logs_webhook_id_webhook_registrations_id_fk"
    FOREIGN KEY ("webhook_id") REFERENCES "webhook_registrations"("id") ON DELETE CASCADE;
END $$;

-- 5. Security tables — created here (custom SQL track) so they exist at
--    startup without requiring a separate drizzle-kit push.
--    The Drizzle schema files (lib/db/src/schema/) own the type definitions.
CREATE TABLE IF NOT EXISTS "data_export_logs" (
  "id"           TEXT PRIMARY KEY,
  "user_id"      TEXT REFERENCES "users"("id") ON DELETE SET NULL,
  "ip"           TEXT NOT NULL DEFAULT 'unknown',
  "user_agent"   TEXT,
  "masked_phone" TEXT,
  "requested_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "completed_at" TIMESTAMPTZ,
  "success"      BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS "idx_data_export_logs_user_id"      ON "data_export_logs" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_data_export_logs_requested_at" ON "data_export_logs" ("requested_at" DESC);

CREATE TABLE IF NOT EXISTS "sentry_known_issues" (
  "fingerprint"   TEXT PRIMARY KEY,
  "title"         TEXT NOT NULL,
  "sentry_id"     TEXT,
  "first_seen_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "last_seen_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "totp_recovery_codes" (
  "id"         TEXT PRIMARY KEY,
  "user_id"    TEXT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "code_hash"  TEXT NOT NULL,
  "used_at"    TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "totp_recovery_codes_user_id_idx" ON "totp_recovery_codes" ("user_id");
